name: watertap-ui-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - nodejs=17.9.0
  - pip:
    - -r backend/requirements.txt
    - git+https://github.com/watertap-org/watertap@workshop_tutorial
