name: App build

on:
  push:
    branches:
      - "new-charts"

defaults:
  run:
    # -l: use login shell (required when using Conda)
    shell: bash -l {0}

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  windows-build:
    name: Windows Build

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment-build.yml
          activate-environment: watertap-ui-env
      
      - name: Install Azure Signtool
        run: |
          dotnet tool install --global AzureSignTool

      - name: Install Electron JS dependencies
        run: |
          npm --prefix electron clean-install

      - name: Install frontend JS dependencies
        run: |
          npm --prefix electron/ui clean-install

      - name: Get idaes extensions
        run: idaes get-extensions

      - name: Install adudchenko/generic treatment train Watertap
        working-directory: ../
        run: git clone https://github.com/avdudchenko/watertap.git && cd watertap && git fetch --all --tags && git checkout generic_treatment_train && pip install --progress-bar off .

      - name: Transfer Entry points
        run: |
          npm --prefix electron run move-entrypoints

      - name: Install watertap-ui Python package
        run: |
          pip install --progress-bar off .

      - name: Build Backend
        run: npm --prefix electron run build-backend

      - name: Build Frontend
        run: npm --prefix electron run build-frontend-win

      - name: Build Windows Distribution
        run: npm --prefix electron run electron-build-win

      - name: Sign Windows Distribution
        run: |
          AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v electron/dist/WaterTAP-UI_24.05.17_win64.exe


      - name: Upload artifact for windows build
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: windows-dist
            path: |
              electron/dist/WaterTAP-UI_24.05.17_win64.exe
